//! Lightweight symbolic tree module.

use anyhow::{Result, bail};
use std::collections::{HashMap, HashSet};
use std::fmt::{Display, Formatter, Result as FmtResult};

use crate::factor::symbolic::SymbolicFactor;

/// Represents the sparsity pattern and topology of the tree.
pub struct SymbolicNode {
    pub main: usize,
    pub separator: Vec<usize>,
    pub factors: Vec<usize>,
    pub children: Vec<SymbolicNode>,
}

pub struct SymbolicTree {
    pub roots: Vec<SymbolicNode>,
}

// pub struct SymbolicFactor {
//     pub vars: Vec<usize>,
// }

impl SymbolicTree {
    /// Builds the symbolic blueprint of the tree.
    /// This is a fast, sequential, purely structural pass.
    /// Note: the variable in order which appear in no factor silently ignored.
    pub fn build<'a>(
        factors: impl IntoIterator<Item = &'a dyn SymbolicFactor>,
        order: &[usize],
    ) -> Result<Self> {
        let factors_vec: Vec<&'a dyn SymbolicFactor> = factors.into_iter().collect();

        // Validate elimination order: check no duplicate
        let seen_in_order: HashSet<&usize> = order.iter().collect();
        if seen_in_order.len() != order.len() {
            bail!("Duplicate variable found in elimination order");
        }

        // Validate that all variables in the factors are accounted for in the order
        let seen_in_factors: HashSet<usize> = factors_vec
            .iter()
            .flat_map(|f| f.vars().iter())
            .cloned()
            .collect();

        for var in &seen_in_factors {
            if !seen_in_order.contains(var) {
                bail!(
                    "Variable {} is present in factors but missing from elimination order",
                    var
                );
            }
        }

        // Drain variable in the elimination order which are present in no factor
        let order: Vec<usize> = order
            .iter()
            .filter(|v| seen_in_factors.contains(v))
            .cloned()
            .collect();

        // Map each variable to its elimination rank: O(1) lookups
        let ranks: HashMap<usize, usize> = order.iter().enumerate().map(|(r, &v)| (v, r)).collect();

        // 2. Assign each original factor to the variable in it that is eliminated FIRST
        let mut factors_map: HashMap<usize, Vec<usize>> = HashMap::with_capacity(order.len());
        for (factor_id, factor) in factors_vec.iter().enumerate() {
            if let Some(&min_var) = factor.vars().iter().min_by_key(|v| ranks.get(v).unwrap()) {
                factors_map.entry(min_var).or_default().push(factor_id);
            }
        }

        let mut separator_map: HashMap<usize, Vec<usize>> = HashMap::with_capacity(order.len());
        let mut children_map: HashMap<usize, Vec<usize>> = HashMap::with_capacity(order.len());
        let mut roots: Vec<usize> = Vec::new();

        // Tracks the symbolic fill-in messages generated by eliminated variables.
        // Stored as (main_var, separator).
        let mut active_messages: Vec<(usize, Vec<usize>)> = Vec::new();

        // 3. Simulate Variable Elimination
        for var in order {
            // Get original factors assigned to this variable
            let var_factors = factors_map.get(&var).cloned().unwrap_or_default();

            // Find and extract all active messages that involve the current variable
            let (var_messages, rem_messages): (Vec<_>, Vec<_>) = active_messages
                .into_iter()
                .partition(|(_, vars)| vars.contains(&var));

            active_messages = rem_messages;

            // The new separator is the union of all involved variables, minus var
            let mut sep_set = HashSet::new();

            for &fid in &var_factors {
                sep_set.extend(factors_vec[fid].vars());
            }
            for (_, var_msg) in &var_messages {
                sep_set.extend(var_msg);
            }
            sep_set.remove(&var);

            let sep_vec: Vec<usize> = sep_set.into_iter().collect();

            // The parent in the tree is the variable in the separator eliminated earliest
            let parent = sep_vec
                .iter()
                .min_by_key(|v| ranks.get(v).unwrap())
                .copied();

            if let Some(p) = parent {
                children_map.entry(p).or_default().push(var);
                // Push the new symbolic message to the active pool (owned Vec)
                active_messages.push((var, sep_vec.clone()));
            } else {
                roots.push(var);
            }

            separator_map.insert(var, sep_vec);
        }

        // 4. Assemble the tree nodes recursively using the computed topology
        let root_nodes = roots
            .into_iter()
            .map(|root_var| Self::build_node(root_var, &children_map, &separator_map, &factors_map))
            .collect();

        Ok(Self { roots: root_nodes })
    }

    fn build_node(
        main: usize,
        children_map: &HashMap<usize, Vec<usize>>,
        separator_map: &HashMap<usize, Vec<usize>>,
        factors_map: &HashMap<usize, Vec<usize>>,
    ) -> SymbolicNode {
        let children = children_map
            .get(&main)
            .unwrap_or(&vec![])
            .iter()
            .map(|&child_var| Self::build_node(child_var, children_map, separator_map, factors_map))
            .collect();

        SymbolicNode {
            main,
            separator: separator_map.get(&main).cloned().unwrap_or_default(),
            factors: factors_map.get(&main).cloned().unwrap_or_default(),
            children,
        }
    }
}

impl Display for SymbolicTree {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        if self.roots.is_empty() {
            return write!(f, "Empty SymbolicTree");
        }

        for (i, root) in self.roots.iter().enumerate() {
            // Print the root node
            writeln!(
                f,
                "Root [Var: {}, Factors: {:?}, Separator: {:?}]",
                root.main, root.factors, root.separator
            )?;

            // Print all children recursively
            let num_children = root.children.len();
            for (j, child) in root.children.iter().enumerate() {
                child.fmt_recursive(f, "", j == num_children - 1)?;
            }

            // Add a blank line between multiple roots
            if i < self.roots.len() - 1 {
                writeln!(f)?;
            }
        }
        Ok(())
    }
}

impl SymbolicNode {
    /// Helper method to recursively format the tree with ASCII branches
    fn fmt_recursive(&self, f: &mut Formatter<'_>, prefix: &str, is_last: bool) -> FmtResult {
        let branch_marker = if is_last { "└── " } else { "├── " };

        writeln!(
            f,
            "{}{}[Main: {}, Factors: {:?}]",
            prefix, branch_marker, self.main, self.factors
        )?;

        let child_prefix = format!("{}{}", prefix, if is_last { "    " } else { "│   " });
        let num_children = self.children.len();

        for (i, child) in self.children.iter().enumerate() {
            child.fmt_recursive(f, &child_prefix, i == num_children - 1)?;
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct SimpleSymbolicFactor {
        vars: Vec<usize>,
    }

    impl SymbolicFactor for SimpleSymbolicFactor {
        fn vars(&self) -> &[usize] {
            &self.vars
        }
    }

    #[test]
    fn test_build_tree() {
        // variables ("x1", 0), ("x2", 1), ("x3", 2), ("l1", 3), ("l2", 4)

        let f0 = SimpleSymbolicFactor { vars: vec![0] };
        let f1 = SimpleSymbolicFactor { vars: vec![0, 1] };
        let f2 = SimpleSymbolicFactor { vars: vec![1, 2] };
        let f3 = SimpleSymbolicFactor { vars: vec![0, 3] };
        let f4 = SimpleSymbolicFactor { vars: vec![1, 3] };
        let f5 = SimpleSymbolicFactor { vars: vec![2, 4] };

        // We can pass references to dyn SymbolicFactor safely
        let symbolic_factors: [&dyn SymbolicFactor; 6] = [&f0, &f1, &f2, &f3, &f4, &f5];

        let tree_result = SymbolicTree::build(symbolic_factors, &[3, 4, 0, 1, 2]);
        assert!(tree_result.is_ok());

        let tree = tree_result.unwrap();
        // Since variable 2 is eliminated last, it acts as the root of the tree
        assert_eq!(tree.roots.len(), 1);
        assert_eq!(tree.roots[0].main, 2);
    }
}
